'''
@author: Matthew Demarest
@version: 1.1
@summary: Events sent to mediator EventManager of demaShapes game.
'''
class Event:
    '''Superclass for any events that might
    be generated by an object and sent to the EventManager
    '''
    def __init__(self):
        self.name = "Generic Event"

class TickEvent(Event):
    def __init__(self):
        self.name = "CPU Tick Event"

class QuitEvent(Event):
    def __init__(self):
        self.name = "Program Quit Event"

class WindowBuiltEvent(Event):
    def __init__(self, window):
        self.name = "Window Finished Building Event"
        self.window = window

class BoardBuiltEvent(Event):
    def __init__(self, board):
        self.name = "Board Finished Building Event"
        self.board = board

class GameStartedEvent(Event):
    def __init__(self, game):
        self.name = "Game Started Event"
        self.game = game

class ShapeStartMoveRequest(Event):
    def __init__(self, direction):
        self.name = "Shape Start Move Request"
        self.direction = direction

class ShapeStopMoveRequest(Event):
    def __init__(self, direction):
        self.name = "Shape Stop Move Request"
        self.direction = direction

class ShapeRotateRequest(Event):
    def __init__(self, direction):
        self.name = "Shape Rotate Request"
        self.direction = direction

class ShapeDropRequest(Event):
    def __init__(self):
        self.name = "Shape Drop Request"

class BoardChanged(Event):
    def __init__(self, activeBlocks, inactiveBlocks):
        self.name = "Board Changed Event"
        self.activeBlocks = activeBlocks
        self.inactiveBlocks = inactiveBlocks

class ScoreUpdateEvent(Event):
    def __init__(self, score):
        self.name = "Score Update Event"
        self.score = score

class ShapeFallEvent(Event):
    ''' Time induced block fall. '''
    def __init__(self):
        self.name = "Shape Fall Event"

class ShapeAddedEvent(Event):
    ''' New shape at top of board '''
    def __init__(self, shape):
        self.shape = shape
        self.name = "Shape Added Event"

class ShapePlacedEvent(Event):
    ''' Shape at bottom. '''
    def __init__(self, shape):
        self.name = "Shape Placed Event"
        self.shape = shape

class ClearedBlocksEvent(Event):
    def __init__(self, rows):
        self.name = "Blocks Cleared Event"
        self.rows = rows
